### ISSUE TITLE
Set simple alarm/monitor checking that our site is up

### ISSUE THREAD

**Issue by amprokop** [VerdanceTeam/verdance-site#10]
Set up the most basic, (no code?) way to do an automated health check on the Verdance site. 

Potentially, this test could visit www.verdance.co and check that the text "We partner with government to build resilient and respectful digital services." is visible.

**Comment by lukey-luke** [comment]
Created uptime robot dashboard [HERE](https://stats.uptimerobot.com/My24e71SiG).

**Comment by amprokop** [comment]
Great!
