### ISSUE TITLE
Verdance logo should pixelate on hover

### ISSUE THREAD

**Issue by amprokop** [VerdanceTeam/verdance-site#11]
<img width="216" alt="image" src="https://github.com/VerdanceTeam/verdance-site/assets/3781835/76eb74f4-5c6c-4a5a-b7f1-6e954c9138e8">

**Comment by amprokop** [comment]
<img width="643" alt="Verdance-logo-hero-pixel@2x (1)" src="https://github.com/VerdanceTeam/verdance-site/assets/3781835/dee3e3a8-5f32-4c9d-9880-09d8a0ddc5ae">
![Verdance-logo-hero-pixel](https://github.com/VerdanceTeam/verdance-site/assets/3781835/e2f9130b-aa31-4df6-8c6d-0ff56e8e7c0b)
![Verdance-logo-hero-pixel (2)](https://github.com/VerdanceTeam/verdance-site/assets/3781835/9dfadd51-f3dd-4d94-83f4-1c06abd51dc6)

**Comment by amprokop** [comment]
![Verdance-logo-hero-pixel](https://github.com/VerdanceTeam/verdance-site/assets/3781835/cbdc751f-d695-4ab3-9c36-beaa7aa9bb80)

**Comment by amprokop** [comment]
![Verdance-logo-hero-pixel (2)](https://github.com/VerdanceTeam/verdance-site/assets/3781835/0e6d354b-13b8-403b-b01a-131798ad9163)

**Comment by amprokop** [comment]
^ three different versions

**Comment by lukey-luke** [comment]
Reached out to Etan about this one regarding using javascript in order to switch to an `<img>` as the pixelated font is not an actual font face AFAIK.

I think we'll wait to see what Matt says before moving forward on this one.

**Comment by etanb** [comment]
Fixed here: https://github.com/VerdanceTeam/verdance-site/pull/37
