### ISSUE TITLE
Take a design pass on spacing

### ISSUE THREAD

**Issue by amprokop** [VerdanceTeam/verdance-site#26]
Some of the elements on the website could use a spacing audit to make sure spacing is appropriate. Let's go through mobile/tablet/desktop and determine where we need to adjust spacing, and note needed changes in this ticket.

**Comment by etanb** [comment]
@Kate-allbee I made this ticket with various ping from @amprokop on spacing: https://github.com/VerdanceTeam/verdance-site/issues/45

I'd like to close this ticket in favor of more specific / actionable github issues, but let me know if you'd like to keep this one open!

**Comment by Kate-allbee** [comment]
@etanb Just seeing this, sorry for the delay! Yes, no problem, we can close this
