### ISSUE TITLE
Increase size of Verdance logo to better match mocks

### ISSUE THREAD

**Issue by amprokop** [VerdanceTeam/verdance-site#27]
Current:

<img width="1362" alt="image" src="https://github.com/user-attachments/assets/be58ce9a-234a-4ed4-a000-3407d98335f7">

Mock:

<img width="1229" alt="image" src="https://github.com/user-attachments/assets/d7de1781-d1d8-4c8e-b8b4-1699ae295b0e">

**Comment by etanb** [comment]
![Screenshot 2024-07-12 at 9 58 24 AM](https://github.com/user-attachments/assets/255468f6-468a-4ee7-bca0-b96c49bd51db)

What numerical discrepancy are you seeing? Maybe we're looking at different Working Files, but as shown above, they're both `font-size: 32px`

**Comment by amprokop** [comment]
Thanks for checking - hmmm I guess high-level it just looks too small to me, as the name of the company it shouldn't be so much smaller than the headline

Opened https://github.com/VerdanceTeam/verdance-site/pull/28 to raise it a bit

**Comment by lukey-luke** [comment]
closing, resolved in https://github.com/VerdanceTeam/verdance-site/pull/28
