### ISSUE TITLE
Update illustration on About us page

### ISSUE THREAD

**Issue by Kate-allbee** [VerdanceTeam/verdance-site#30]
### Issue
On the current page, the illustration in the bottom module is not matching the background color for this section. 
<img width="1000" alt="image" src="https://github.com/user-attachments/assets/cbaaabd8-f3e7-4fbe-8cb9-5da82cc28bd0">

We recieved an updated illustration to fit this background from Maycon. Attached to this ticket. 
Illustration needs to be swapped out for new one. 

[
![Mid-size-Gears-v2-640x360px-x2](https://github.com/user-attachments/assets/b4b46830-dc3b-4290-80ad-e6e634dd45e3)
](url)

**Comment by lukey-luke** [comment]
We might want to change it up a bit. It looks like the same illustration is used on the site twice currently. I submitted a PR to fix the clashing background color, but happy to submit follow up to change to a new illustration or whatever.


<img width="1503" alt="Screenshot 2024-07-17 at 5 08 17 PM" src="https://github.com/user-attachments/assets/4a2ed2da-b309-4196-b697-ab03a58b7210">
<img width="1509" alt="Screenshot 2024-07-17 at 5 08 27 PM" src="https://github.com/user-attachments/assets/56fc9b17-d536-4dd9-8e5e-e5ed8425df04">

**Comment by lukey-luke** [comment]
Latest .webp w/ transparent background used in #33. Will update illustrations in next round of design specs.
