### ISSUE TITLE
Secondary font seems to fallback to Times New Roman or similar on mobile

### ISSUE THREAD

**Issue by amprokop** [VerdanceTeam/verdance-site#36]
![image](https://github.com/user-attachments/assets/05320780-c858-48a6-a08e-38fd9b1b1436)

Tested on my iPhone - see the "WHO WE SERVE FONT" - it should match the font seen on desktop:

**Comment by amprokop** [comment]
<img width="1166" alt="image" src="https://github.com/user-attachments/assets/e83e2b72-0342-4a7b-9504-8c0e377118ba">

**Comment by lukey-luke** [comment]
Issue does not occur w/ mobile view for chrome on Desktop. I can confirm I was able to reproduce this issue on a physical iOS device.

**Comment by lukey-luke** [comment]
I think it may be the case that `Tahoma` isn't loaded on mobile, but it does on Desktop. Upon further inspection of UI spec on [figma](https://www.figma.com/design/UWnSkvot0qIkjqFC7PzSHR/Verdance-website-2.0-sandbox?node-id=40-10166&t=YgfqKGVpqGQloWgG-0), it looks like the more pixelated font `PPNeueBit-Bold` should be preferred.

Figma Screenshot:
![Screenshot 2024-08-05 at 3 22 07 PM](https://github.com/user-attachments/assets/42c07c9f-4fef-4017-aeb5-96e1ae7f9955)


Using `font-family: 'PPNeueBit-Bold', 'Brush Script MT';` indicates that `'PPNeueBit-Bold'` is not being loaded properly (even on desktop)
![Screenshot 2024-08-05 at 3 23 34 PM](https://github.com/user-attachments/assets/84c4288e-99bd-4e54-96cc-77402cae31d0)
