### ISSUE TITLE
[footer] Make white footer text bigger & redo yellow graphic V, probably removing the text

### ISSUE THREAD

**Issue by amprokop** [VerdanceTeam/verdance-site#9]
Redo footer to match the new designs:

<img width="895" alt="image" src="https://github.com/user-attachments/assets/a56d411e-7d98-4969-aaa6-c8b8ad77fd0b">

https://www.figma.com/design/UWnSkvot0qIkjqFC7PzSHR/Verdance-website-2.0-sandbox?node-id=677-2126&t=UpJNxs07CWVl4KWj-0

**Comment by Kate-allbee** [comment]
Update to the type size that we see in the header and footer
[Figma Link
](https://www.figma.com/design/UWnSkvot0qIkjqFC7PzSHR/Verdance-website-2.0-sandbox?node-id=677-2126&t=JiXXVhQ5mxnQgSjx-1)

**Header**

![image](https://github.com/user-attachments/assets/2a4e844f-aea8-4242-aab7-0426191e209a)
- Increased the type size here to 16px

![image](https://github.com/user-attachments/assets/58a65579-44fc-408f-ae97-91081c76bada)
- Increased the size of these corresponding icons to 12px x 12px


**Footer**

![image](https://github.com/user-attachments/assets/c57769f9-0503-4b73-86fa-6414c0fa0851)
- Increased the type size here to 16px

![image](https://github.com/user-attachments/assets/5afc1b1a-4cf9-4ff0-a189-b3982202c717)
- Increased the type size here to 16px, and increased the size of icons to 12px x 12px

**Comment by Kate-allbee** [comment]
Yellow V to swap in for the typography V
[Link Here](https://www.figma.com/design/UWnSkvot0qIkjqFC7PzSHR/Verdance-website-2.0-sandbox?node-id=677-2126&t=JiXXVhQ5mxnQgSjx-1)
